// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkykyafrphsrvrzncovu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJreWt5YWZycGhzcnZyem5jb3Z1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NTU4MDgsImV4cCI6MjA2NjAzMTgwOH0.7HcEbDmSlkQ3SOgxOTpIGrxAIK3Z6bwKK2Gwtqddtck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);